### ISSUE TITLE
Domanda QGIS  "Unione con un singolo strato"

### ISSUE THREAD

**Issue by aborruso** [aborruso/appunti#3]
@pigreco l'unione con singolo strato è questa?

![image](https://user-images.githubusercontent.com/30607/71530778-e86b6780-28eb-11ea-8191-8e97670e3360.png)

Grazie

**Comment by pigreco** [comment]
Caro @aborruso 
sì.

**Comment by pigreco** [comment]
il layer di sovrapposizione è opzionale
![image](https://user-images.githubusercontent.com/7631137/71531842-cfb18080-28f0-11ea-98d6-df5936cc2891.png)

**Comment by aborruso** [comment]
Grazie
