### ISSUE TITLE
Impostazione modello grafico QGIS

### ISSUE THREAD

**Issue by aborruso** [aborruso/appunti#4]
Caro @pigreco ,
ho aperto un mio progetto QGIS (quello che trovi [qui](https://github.com/aborruso/appunti/tree/master/bozze/unione-mapshaper))  e poi ho usato il tuo modello grafico.

In output il vettore ha coordinate in 4326, ma è associato a 32633.

È come se prendesse l'EPSG del progetto QGIS e non le proprie. Se è così, mi sembra da correggere

**Comment by pigreco** [comment]
Caro @aborruso 

> È come se prendesse l'EPSG del progetto QGIS e non le proprie. Se è così, mi sembra da correggere

esatto, provvedo subito.

**Comment by pigreco** [comment]
funziona benissimo, (@aborruso )

![image](https://user-images.githubusercontent.com/7631137/71531750-6893cc00-28f0-11ea-98cf-8e6d73a5bff3.png)
